<?php
/**
 * Created by PhpStorm.
 * User: Duncan
 * Date: 2019/2/25
 * Time: 16:14
 */

namespace app\admin\controller;
use think\Controller;

class Deal extends Controller {
    private $category_model = null;
    private $city_model = null;
    private $deal_model = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->category_model = new \app\common\model\Category();
        $this->city_model = new \app\common\model\City();
        $this->deal_model = new \app\common\model\Deal();
    }

    public function index() {
        $data = input('get.');
        $categories = $this->category_model->getFirstCategorysName();
        $cities = $this->city_model->getCitiesFather();
        $categories_index = [];
        foreach ($categories as $key) {
            $categories_index[$key->id] = $key->name;
        }
        $cities_index = [];
        foreach ($cities as $key) {
            $cities_index[$key->id] = $key->name;
        }
        $get_data = [];
        $fliter_data = [];
        if (!empty($data['start_time'])) {
            $get_data['start_time'] = strtotime($data['start_time']);
            array_push($fliter_data, ['start_time', '>' , $get_data['start_time']]);
        }

        if (!empty($data['end_time'])) {
            $get_data['end_time'] = strtotime($data['end_time']);
            array_push($fliter_data, ['end_time', '<', $get_data['end_time']]);
        }

        if (!empty($data['end_time']) && !empty($data['start_time']) && $get_data['end_time'] < $get_data['start_time'])
        {
            $this->error("时间错误");
        }

        if (!empty($data['category_id'])){
            $get_data['category_id'] = $data['category_id'];
            array_push($fliter_data, ['category_id' , '=', $get_data['category_id']]);
        }

        if (!empty($data['city_id'])) {
            $get_data['city_id'] = $data['city_id'];
            array_push($fliter_data, ['city_id', '=', $get_data['city_id']]);
        }

        if (!empty($data['name'])) {
            $get_data['name'] = $data['name'];
            array_push($fliter_data, ['name', 'like', '%'.$get_data['name'].'%']);
        }

        $deal_data = $this->deal_model->getDealInfo($fliter_data);
        $this->assign('page', $deal_data->render());
        $this->assign("category_index", $categories_index);
        $this->assign("cities_index", $categories_index);
        $this->assign('city_id', empty($get_data['city_id'])?'': $get_data['city_id']);
        $this->assign('category_id' ,empty($get_data['category_id'])?'': $get_data['category_id']);
        $this->assign('start_time' ,empty($data['start_time'])?'': $data['start_time']);
        $this->assign('end_time' ,empty($data['end_time'])?'': $data['end_time']);
        $this->assign('name' ,empty($get_data['name'])?'': $get_data['name']);
        $this->assign("categories", $categories);
        $this->assign("cities", $cities);
        $this->assign("deal_data", $deal_data);
        return $this->fetch();
    }



    public function updateStatus()
    {
        $data = input("get.");
        $res = $this->deal_model->updateDealById($data);

        if (!$res) {
            $this->error("操作失败");
        }

        $this->success("操作成功");
    }
}