<?php
/**
 * Created by PhpStorm.
 * User: Duncan
 * Date: 2019/2/22
 * Time: 17:26
 */
namespace app\index\controller;


use app\bis\controller\Location;
use app\common\model\BisLocation;
use app\common\model\Category;
use app\common\model\Deal;

class Detail extends Base {
    private $deal_model = null;
    private $category_model = null;
    private $location_model = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->deal_model = new Deal();
        $this->category_model = new Category();
        $this->location_model = new BisLocation();
    }


    public function index($id) {
        $deal_info = $this->deal_model->getSingleById($id);
        $category = $this->category_model->getCategoryById($deal_info->category_id);
        $location_ids = $this->location_model->getLocationNames(explode(',', $deal_info->location_ids));
        $flag = 0;//判断是否开始
        $time_data = '';
        if ($deal_info->start_time > time()) {
            $flag = 1;
            $dtime = $deal_info->start_time-time();
            $d = floor($dtime / (3600 *  24));
            if($d) {
                $time_data .= $d . "天 ";
            }
            $h = floor($dtime%(3600*24)/3600);
            if ($h) {
                $time_data .= $h . "小时 ";
            }
            $m = floor($dtime%(3600*24)%3600/60);
            if ($m) {
                $time_data .= $m . "分 ";
            }
        }

        if (empty($location_ids)) {
            $this->error("该商品已经下架，分店已经被撤出");
        }
        $this->assign("time_data", $time_data);
        $this->assign("overplus", ($deal_info->total_count - $deal_info->buy_count));
        $this->assign("location_ids", $location_ids);
        $this->assign("deal", $deal_info);
        $this->assign("category", $category);
        $this->assign("title", $deal_info->name);
        $this->assign("flag", $flag);
        $this->assign("map_info", $location_ids[0]['xpoint'] . "," . $location_ids[0]['ypoint']);
        return $this->fetch();
    }


}