<?php
namespace app\index\controller;

use app\common\model\Deal;
use app\common\model\Featured;

class Index extends Base
{
    private $deal_model = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->deal_model = new Deal();
    }

    public function index()
    {
        $feature_model = new Featured();
        $big_pic = $feature_model->getPicByType(0);
        $ad_pic = $feature_model->getPicByType(1);
        $city_id = empty(input("get.city_id")) ? '17' : input("get.city_id");
        $deals = $this->getDeals(1, $city_id);
        $this->mixCategroy();
        $this->assign("deals", $deals);
        $this->assign("big_pic", $big_pic);
        $this->assign("ad_pic", $ad_pic);
        return $this->fetch();
    }

    /**
     * 获取商品数据
     */
    public function getDeals($id, $city_id) {
        $data = $this->deal_model->getNormalDealByCategoryCityId($id, $city_id);
        return $data;
    }
}
