<?php
/**
 * Created by PhpStorm.
 * User: Duncan
 * Date: 2019/2/23
 * Time: 20:07
 */

namespace app\index\controller;

use app\common\model\Category;
use app\common\model\Deal;

class Lists extends Base {
    private $category_model = null;
    private $deal_model = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->category_model = new Category();
        $this->deal_model = new Deal();
    }

    public function index() {
        //获取一级栏目
        $firstCatIds = [];
        $data = [
            'city_id' => $this->city_id
        ];
        $categorys =  $this->category_model->getFirstCategorysName();
        foreach ($categorys as $key) {
            $firstCatIds[] = $key->id;
        }
        $id = input('id', 0 , 'intval');
        if (in_array($id, $firstCatIds)) {
            //一级分类
            $category_parent_id = $id;
            $data['category_id'] = $id;
        } else if ($id) {
            //二级分类
            $category = $this->category_model->get($id);
            if (!$category || $category->status != 1) {
                $this->error("数据不合法");
            }
            $category_parent_id = $category->parent_id;
            $data['se_category_id'] = $id;
        } else {
            //0
            $category_parent_id = 0;
        }

        $se_categories = [];
        //获取子分类
        if ($category_parent_id) {
            $se_categories = $this->category_model->getFirstCategorysName($category_parent_id);
        }
        $sales['order_sales'] = input("order_sales");
        $sales['order_price'] = input("order_price");
        $sales['order_time'] = input("order_time");
        /**
         * 获取商品的信息
         */
        $deals = $this->deal_model->getDealByCondition($data, $sales);
        $page = $deals->appends($this->request->param())->render();
        $this->assign("deals", $deals);
        $this->assign("page", $page);
        $this->assign("se_categories", $se_categories);
        $this->assign("categorys", $categorys);
        $this->assign('id', $id);
        $this->assign('category_parent_id', $category_parent_id);
        $this->assign("order_flag", $this->getListOrder($sales));
        return $this->fetch();
    }

    /**
     * 排序数据获取的逻辑
     */
    public function getListOrder($data){
        if (!empty($data['order_sales'])) {
            $order_flag = 'order_sales';
        } else if(!empty($data['order_price'])) {
            $order_flag = 'order_price';
        } else if (!empty($data['order_time'])) {
            $order_flag = 'order_time';
        } else {
            $order_flag = '';
        }

        return $order_flag;
    }
}