<?php
/**
 * Created by PhpStorm.
 * User: Duncan
 * Date: 2019/3/1
 * Time: 9:51
 */

/**
 * 一些全局的设置
 */

namespace app\bis\controller;

use think\Controller;

class Base extends Controller
{
    private $account;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->getUserInfo();
        if ($this->isLogin()) {
            return $this->redirect(url("bis/login/index"));
        }
    }

    public function isLogin()
    {
        if ($this->getUserInfo()) {
            return false;
        }

        return true;
    }

    public function getUserInfo() {
        $account_info = session('account_info','', 'bis');
        if (!$this->account) {
            $this->account = $account_info;
        }
        return $this->account;
    }



}