<?php
/**
 * Created by PhpStorm.
 * User: Duncan
 * Date: 2019/2/23
 * Time: 20:00
 */
namespace app\bis\controller;
use app\common\model\BisLocation;
use app\common\model\Category;
use app\common\model\City;
use think\Controller;

class Deal extends Base {

    private $deal_validate = null;
    private $city_model = null;
    private $category_model = null;
    private $location_model = null;
    private $deal_model = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->deal_validate = new \app\bis\validate\Deal();
        $this->city_model =  new City();
        $this->category_model = new Category();
        $this->location_model = new BisLocation();
        $this->deal_model = new \app\common\model\Deal();
    }

    public function add () {
        $cities = $this->city_model->getCitiesFather();
        $categories = $this->category_model->getFirstCategorysName();
        $this->assign("se_bis", $this->getSeBis());
        $this->assign("cities", $cities);
        $this->assign("categories", $categories);
        return $this->fetch();
    }

    public function index() {
        /**
         * 获取该门店的所有商品
         */
        $data['bis_id'] = $this->getUserInfo()->bis_id;
        $info = $this->deal_model->getAllDeals($data);
        $this->assign("info", $info);
        return $this->fetch();
    }

    public function save() {
        $data = input('post.');
        $res_validate = $this->deal_validate->scene('add')->check($data);
        if (!$res_validate) {
            $this->error($this->deal_validate->getError());
        }

        /**
         * 地址？？？
         */
        $data['location_ids'] = empty($data['se_bis_id']) ? '' : implode(',', $data['se_bis_id']);
        $data['se_category_id'] = empty($data['se_category_id']) ? '' : implode(',', $data['se_category_id']);
        $data['bis_id'] = $this->getUserInfo()->bis_id;
        $data['start_time'] = strtotime($data['start_time']);
        $data['end_time'] = strtotime($data['end_time']);
        $data['coupons_begin_time'] = strtotime($data['coupons_begin_time']);
        $data['coupons_end_time'] = strtotime($data['coupons_end_time']);
        $data['bis_account_id'] = $this->getUserInfo()->id;
        $data['city_id'] = $data['se_city_id'];
        $res = $this->deal_model->addDeal($data);
        if (!$res) {
            $this->error("添加失败");
        }else {
            $this->success("添加成功");
        }

    }

    /**
     * 获取门店
     */
    public function getSeBis() {
        $user_info = $this->getUserInfo();
        $parent_id = $user_info['bis_id'];
        $se_bis = $this->location_model->getLocationByParentId($parent_id);
        return $se_bis;
    }

    public function detail() {
        return $this->fetch();
    }
 }