<?php
/**
 * Created by PhpStorm.
 * User: Duncan
 * Date: 2019/2/23
 * Time: 20:01
 */
namespace app\bis\controller;
use app\common\model\BisLocation;
use app\common\model\Category;
use app\common\model\City;
use Map\Map;

class Location extends Base {
    private $city_model = null;
    private $category_model = null;
    private $location_validate = null;
    private $user_info = null;
    private $map = null;
    private $bis_location_model = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->city_model =  new City();
        $this->category_model = new Category();
        $this->location_validate = new \app\bis\validate\Location();
        $this->user_info = $this->getUserInfo();
        $this->map = new Map();
        $this->bis_location_model = new BisLocation();
    }

    public function add() {
        $cities = $this->city_model->getCitiesFather();
        $categories = $this->category_model->getFirstCategorysName();
        $this->assign("cities", $cities);
        $this->assign("categories", $categories);
        return $this->fetch();
    }

    /**
     * @return mixed
     * 获取分店的列表
     */
    public function index() {
        $parent_id = $this->user_info['bis_id'];
        $se_bis_data = $this->bis_location_model->getLocationByParentId($parent_id);
        $this->assign('se_bis_data', $se_bis_data);
        return $this->fetch();
    }

    public function save() {
        $data = input("post.", '', 'htmlentities');
        $res_validate = $this->location_validate->scene("add")->check($data);
        if (!$res_validate) {
            $this->error($this->location_validate->getError());
        }

        $post_data = $data;
        $categroy_path = $data['category_id'];
        $se_category_ids = implode(',', $data['se_category_id']);
        $post_data['category_path'] = $categroy_path . ',' . (empty($se_category_ids) ? '' : $se_category_ids);
        $id = $this->user_info['bis_id'];
        $post_data['parent_id'] = $id;
//获取经纬度
        $location_lang = $this->map->getLatLong($data['address']);
        $location_result = $location_lang->result;
        if (empty($location_lang) || $location_lang->status != 0 || $location_result->precise != 1){
            $this->error("无法获取数据，或者匹配的地址不准确.");
        }

        $post_data['xpoint'] = $location_result->location->lng;
        $post_data['ypoint'] = $location_result->location->lat;
        $post_data['city_path'] = $data['city_id'] . ',' . (empty($data['se_city_id']) ? '' : $data['se_city_id']);
        $post_data['content'] = $data['description'];
        $res = $this->bis_location_model->addSeBis($post_data);
        if (!$res) {
            $this->error("添加门店失败");
        }

        $this->success("添加门店成功");
    }


    public function updateStatus() {
        $data = input('get.');
        if (empty($data)) {
            $this->error("未收到修改的信息");
        }

        $res = $this->bis_location_model->updateBisLocation($data);
        if (!$res) {
            $this->error("修改失败");
        }

        $this->success("操作成功");
    }

    /**
     * 详情页面
     */
    public function detail($id) {
        $se_bis_location = $this->bis_location_model->getSeLocationByBisId($id);
        $content = html_entity_decode($se_bis_location['content']);
        $city_path = explode(",", $se_bis_location['city_path']);
        $city = $this->city_model->getCityById($city_path[0]);
        $se_city = $this->city_model->getCityById($city_path[1]);

        $category_path = explode(",", $se_bis_location['category_path']);
        $se_category = [];
        $category = $this->category_model->getCategoryById($category_path[0]);
        if (!empty($category_path[1])) {
            foreach ($category_path as $key=>$value){
                if ($key != 0) {
                    array_push($se_category, $this->category_model->getCategoryById($value));
                }
            }
        }

        $this->assign("category", $category);
        $this->assign("se_category", $se_category);
        $this->assign("content", $content);
        $this->assign("city", $city);
        $this->assign("se_city", $se_city);
        $this->assign("se_bis_location", $se_bis_location);
        return $this->fetch();
    }
}